### ISSUE TITLE
Je peux désinscrire une équipe d'un événement sans en faire partie

### ISSUE THREAD

**Issue by qriosserra** [qriosserra/nooble#3]
# What I do

```json
{
  "roles": [
    "ROLE_USER"
  ],
  "email": "test@test.com"
}
```

`DELETE` `/api/team_registrations/1`

# Observed behavior

L'équipe est désinscrite de l'événement.

# Expected behavior

Je ne devrais pas pouvoir désinscrire une équipe dont je ne fais pas partie à moins d'être l'organisateur de l'événement.

# Hint

Voir dans dans [src/Security/Voter/TeamRegistrationVoter:63](https://github.com/qriosserra/nooble/blob/main/src/Security/Voter/TeamRegistrationVoter.php#L63)

**Comment by Ggking360** [comment]
J'ai ajouté le voter existant à la classe Member et limité les droits aux administrateurs ainsi qu'aux utilisateurs associés.

**Comment by Ggking360** [comment]
mb
